-- Criação da Tabela de Grade Diária
create table public.daily_schedule (
  id bigint generated by default as identity primary key,
  schedule_date date not null unique,
  total_duration_seconds integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Criação da Tabela de Itens da Grade
create table public.schedule_items (
  id bigint generated by default as identity primary key,
  daily_schedule_id bigint references public.daily_schedule(id) on delete cascade not null,
  title text not null,
  video_url text not null,
  duration_seconds integer not null,
  start_time_seconds integer not null,
  sort_order integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Políticas de Segurança (RLS) - Permitindo acesso total para testes
alter table public.daily_schedule enable row level security;
alter table public.schedule_items enable row level security;

create policy "Enable all access for daily_schedule" 
on public.daily_schedule for all 
using (true) with check (true);

create policy "Enable all access for schedule_items" 
on public.schedule_items for all 
using (true) with check (true);
